export { default as App } from './App'
export { default as Register } from './Register'
export { default as Login } from  './Login'
export { PrivateRoute } from './PrivateRoute'
export { default as Home } from './Home'
export { default as setAuthToken } from './Auth'